    
services:
  - docker

jobs:
  include:
    - stage: build
      language: minimal
      script:
        - docker build -t api-panel .
        - echo $DOCKER_PASSWORD | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker tag api-panel $DOCKER_USERNAME/api-panel
        - docker push $DOCKER_USERNAME/api-panel





